/*
 * This java source file is generated by DAO4J v1.19
 * Generated on Tue Mar 06 02:03:08 CST 2018
 * For more information, please contact b-i-d@163.com
 * Please check http://sourceforge.net/projects/dao4j/ for the latest version.
 */

package dao4j.sample;

public class TiempoKey implements java.io.Serializable, Cloneable {
    /* hora */
    protected java.util.Date hora;

    /* hora */
    public java.util.Date getHora() {
        return hora;
    }

    /* hora */
    public void setHora(java.util.Date hora) {
        this.hora = hora;
    }

    /* Calculate hash code */
    public int hashCode() {
        int hashCode = 0;
        if (hora != null)  
            hashCode += hora.hashCode();
        return hashCode;
    }
    
    /* Indicates whether some other object is "equal to" this one. */
    public boolean equals(Object obj) {
        if (this == obj)
            return true;

        if (obj == null || !(obj instanceof TiempoKey))
            return false;

        TiempoKey key = (TiempoKey) obj;

        if (this.hora == null) {
            if (key.hora != null)
                return false;
        }
        else if (!this.hora.equals(key.hora)) 
            return false;

        return true;
    }

    /* Creates and returns a copy of this object. */
    public Object clone()
    {
        TiempoKey key = new TiempoKey();
        if (this.hora != null)
            key.hora = (java.util.Date) this.hora.clone();
        return key;
    }

    /* Returns a string representation of the object. */
    public String toString() {
        String sep = "\r\n";
        StringBuffer sb = new StringBuffer();
        sb.append(this.getClass().getName()).append(sep);
        sb.append("[").append("hora").append(" = ").append(hora).append("]");
        return sb.toString();
    }
}