/*
 * This java source file is generated by DAO4J v1.19
 * Generated on Tue Mar 06 02:03:08 CST 2018
 * For more information, please contact b-i-d@163.com
 * Please check http://sourceforge.net/projects/dao4j/ for the latest version.
 */

package dao4j.sample;

/*
 * For Table Tiempo
 */
public class Tiempo implements java.io.Serializable, Cloneable {
    private TiempoKey _key = new TiempoKey();

    /* hora, PK */
    protected java.util.Date hora;

    /* Return the key object. */
    public TiempoKey getKeyObject() {
        return _key;
    }

    /* hora, PK */
    public java.util.Date getHora() {
        return hora;
    }

    /* hora, PK */
    public void setHora(java.util.Date hora) {
        this.hora = hora;
        _key.setHora(hora);
    }

    /* Indicates whether some other object is "equal to" this one. */
    public boolean equals(Object obj) {
        if (this == obj)
            return true;

        if (obj == null || !(obj instanceof Tiempo))
            return false;

        Tiempo bean = (Tiempo) obj;

        if (this.hora == null) {
            if (bean.hora != null)
                return false;
        }
        else if (!this.hora.equals(bean.hora)) 
            return false;

        return true;
    }

    /* Creates and returns a copy of this object. */
    public Object clone()
    {
        Tiempo bean = new Tiempo();
        if (this.hora != null)
            bean.hora = (java.util.Date) this.hora.clone();
        return bean;
    }

    /* Returns a string representation of the object. */
    public String toString() {
        String sep = "\r\n";
        StringBuffer sb = new StringBuffer();
        sb.append(this.getClass().getName()).append(sep);
        sb.append("[").append("hora").append(" = ").append(hora).append("]").append(sep);
        return sb.toString();
    }
}