    /*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import interfaces.InterfazDeVentas;
import interfaces.interfazAdministrarMercancia;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Categoria;
import modelo.Proveedor;

/**
 *
 * @author rosario
 */
public class PanelVentas extends javax.swing.JFrame {

    /**
     * Creates new form login
     * 
     */
    
       
    private InterfazDeVentas unaInterfazDeVentas;
    private DefaultTableModel modeloTablaDeBusqueda;
    private DefaultTableModel modeloTablaDeCompra;
    private Date fecha;
    
    

    public PanelVentas(){
        
    }
    public PanelVentas(InterfazDeVentas unaInterfazDeVentas) {
        
        int trimestre =0;
        this.unaInterfazDeVentas = unaInterfazDeVentas;
        initComponents();
        
        fecha = new Date();
        
        trimestre = (fecha.getMonth()/4)+1;
        
        lblAnio.setText(String.valueOf(fecha.getYear()+1900) );
        lblTrimestre.setText(String.valueOf(trimestre) );
        
        lblIdVenta.setText( String.valueOf(unaInterfazDeVentas.calcularIdVenta(lblTienda.getText(), Integer.parseInt(lblAnio.getText()),
                Integer.parseInt(lblTrimestre.getText()))) ); 
        
        
        modeloTablaDeBusqueda = (DefaultTableModel)tablaBusquedaArticulos.getModel();
        modeloTablaDeBusqueda.setRowCount(0);
        modeloTablaDeCompra = (DefaultTableModel)tablaArticulos.getModel();
        modeloTablaDeCompra.setRowCount(0);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaBusquedaArticulos = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaArticulos = new javax.swing.JTable();
        rbBuscarEnOtrasTiendas = new javax.swing.JRadioButton();
        rbCategoria = new javax.swing.JRadioButton();
        btnBuscar = new javax.swing.JButton();
        comboProveedor = new javax.swing.JComboBox<>();
        comboCategoria = new javax.swing.JComboBox<>();
        btnRegistrarVenta = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lblTienda = new javax.swing.JLabel();
        lblImporte = new javax.swing.JLabel();
        rbProveedor = new javax.swing.JRadioButton();
        txtNombre = new javax.swing.JTextField();
        rbNombre = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        lblIdVenta = new javax.swing.JLabel();
        btnEliminar = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        lblCURP = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        lblAnio = new javax.swing.JLabel();
        lblTrimestre = new javax.swing.JLabel();

        jLabel4.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 51, 0));
        jLabel4.setText("Bienvenido");

        jLabel10.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(153, 51, 0));
        jLabel10.setText("Bienvenido");

        jLabel11.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(153, 51, 0));
        jLabel11.setText("Carrito de compra");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 51, 0));
        jLabel3.setText("Bienvenido");

        lblNombre.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblNombre.setForeground(new java.awt.Color(153, 51, 0));
        lblNombre.setText("nombre");

        jLabel5.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 51, 0));
        jLabel5.setText("Busqueda:");

        jLabel6.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(153, 51, 0));
        jLabel6.setText("Carrito de compra");

        jScrollPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jScrollPane1MouseClicked(evt);
            }
        });

        tablaBusquedaArticulos.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        tablaBusquedaArticulos.setForeground(new java.awt.Color(153, 51, 0));
        tablaBusquedaArticulos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Nombre", "Categoria", "Proveedor", "Precio", "Existencias"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaBusquedaArticulos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaBusquedaArticulosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaBusquedaArticulos);

        tablaArticulos.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        tablaArticulos.setForeground(new java.awt.Color(153, 51, 0));
        tablaArticulos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Nombre Producto", "Proveedor", "Precio", "No Piezas", "Existencias"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaArticulos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tablaArticulosMousePressed(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaArticulosMouseClicked(evt);
            }
        });
        tablaArticulos.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                tablaArticulosInputMethodTextChanged(evt);
            }
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
        });
        jScrollPane2.setViewportView(tablaArticulos);

        rbBuscarEnOtrasTiendas.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        rbBuscarEnOtrasTiendas.setForeground(new java.awt.Color(153, 51, 0));
        rbBuscarEnOtrasTiendas.setText("Buscar En Otras Tiendas");
        rbBuscarEnOtrasTiendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbBuscarEnOtrasTiendasActionPerformed(evt);
            }
        });

        rbCategoria.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        rbCategoria.setForeground(new java.awt.Color(153, 51, 0));
        rbCategoria.setText("Categoria");

        btnBuscar.setBackground(new java.awt.Color(153, 51, 0));
        btnBuscar.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        btnBuscar.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        comboProveedor.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        comboProveedor.setForeground(new java.awt.Color(153, 51, 0));
        comboProveedor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        comboCategoria.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        comboCategoria.setForeground(new java.awt.Color(153, 51, 0));
        comboCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboCategoriaActionPerformed(evt);
            }
        });

        btnRegistrarVenta.setBackground(new java.awt.Color(153, 51, 0));
        btnRegistrarVenta.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        btnRegistrarVenta.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrarVenta.setText("Finalizar");
        btnRegistrarVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarVentaActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(153, 51, 0));
        jLabel7.setText("Sucursal:");

        jLabel8.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(153, 51, 0));
        jLabel8.setText("ID venta:");

        lblTienda.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblTienda.setForeground(new java.awt.Color(153, 51, 0));
        lblTienda.setText("Anderson-Mitchell");

        lblImporte.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblImporte.setForeground(new java.awt.Color(153, 51, 0));
        lblImporte.setText("$0");
        lblImporte.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblImporteMouseClicked(evt);
            }
        });

        rbProveedor.setText("Proveedor");

        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });

        rbNombre.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        rbNombre.setForeground(new java.awt.Color(153, 51, 0));
        rbNombre.setText("Nombre");

        jLabel9.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(153, 51, 0));
        jLabel9.setText("Importe de la venta");

        lblIdVenta.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblIdVenta.setForeground(new java.awt.Color(153, 51, 0));
        lblIdVenta.setText("1");

        btnEliminar.setText("Quitar Articulo");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(153, 51, 0));
        jLabel12.setText("CURP");

        lblCURP.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblCURP.setForeground(new java.awt.Color(153, 51, 0));
        lblCURP.setText("ACPM592338XMIDAR46");

        jLabel13.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(153, 51, 0));
        jLabel13.setText("Anio");

        jLabel14.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(153, 51, 0));
        jLabel14.setText("Trimestre");

        lblAnio.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblAnio.setForeground(new java.awt.Color(153, 51, 0));
        lblAnio.setText("2017");

        lblTrimestre.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblTrimestre.setForeground(new java.awt.Color(153, 51, 0));
        lblTrimestre.setText("1");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rbProveedor)
                                    .addComponent(rbCategoria)
                                    .addComponent(jLabel5)
                                    .addComponent(rbNombre))
                                .addGap(66, 66, 66)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rbBuscarEnOtrasTiendas)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(comboCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(comboProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblNombre)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblCURP)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                    .addGap(53, 53, 53)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel8)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addGroup(jPanel2Layout.createSequentialGroup()
                                                    .addGap(0, 0, Short.MAX_VALUE)
                                                    .addComponent(lblTrimestre, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                                    .addComponent(jLabel13)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(lblAnio))
                                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel6)
                                                        .addComponent(jLabel14))
                                                    .addGap(0, 0, Short.MAX_VALUE)))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(btnEliminar)
                                                .addComponent(btnRegistrarVenta)))))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(lblImporte))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                    .addGap(51, 51, 51)
                                    .addComponent(jLabel7)
                                    .addGap(39, 39, 39)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblIdVenta)
                                        .addComponent(lblTienda))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(53, 53, 53)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNombre)
                            .addComponent(jLabel3)
                            .addComponent(jLabel12)
                            .addComponent(lblCURP)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblTienda)
                        .addComponent(jLabel7)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(lblIdVenta))
                        .addGap(4, 4, 4))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(rbBuscarEnOtrasTiendas))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar)
                    .addComponent(rbNombre)
                    .addComponent(jLabel6)
                    .addComponent(btnRegistrarVenta))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(comboCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rbCategoria)
                            .addComponent(btnEliminar))
                        .addGap(18, 18, 18))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(lblAnio))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(lblTrimestre))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbProveedor)
                    .addComponent(jLabel9)
                    .addComponent(lblImporte))
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 60, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 13, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        int tipoBusqueda;
        if(!rbBuscarEnOtrasTiendas.isSelected()&&rbNombre.isSelected()&&rbProveedor.isSelected()&&!rbCategoria.isSelected()){
            unaInterfazDeVentas.buscarProducto(lblTienda.getText(), txtNombre.getText(), (String) comboProveedor.getSelectedItem(), 1);
        }else if(!rbBuscarEnOtrasTiendas.isSelected()&&rbNombre.isSelected()&&!rbProveedor.isSelected()&&!rbCategoria.isSelected()){
            unaInterfazDeVentas.buscarProducto(lblTienda.getText(), txtNombre.getText(), 1);
        }else if(!rbBuscarEnOtrasTiendas.isSelected()&&!rbNombre.isSelected()&&rbProveedor.isSelected()&&!rbCategoria.isSelected()){
            unaInterfazDeVentas.buscarProducto(lblTienda.getText(), (String)comboProveedor.getSelectedItem(), 2);
        }else if(!rbBuscarEnOtrasTiendas.isSelected()&&!rbNombre.isSelected()&&!rbProveedor.isSelected()&&rbCategoria.isSelected()){
            unaInterfazDeVentas.buscarProducto(lblTienda.getText(), (String)comboCategoria.getSelectedItem(), 3);
        }else if(rbBuscarEnOtrasTiendas.isSelected()&&rbNombre.isSelected()&&rbProveedor.isSelected()&&!rbCategoria.isSelected()){
            unaInterfazDeVentas.buscarProductoEnTodasLasTiendas(txtNombre.getText(), (String) comboProveedor.getSelectedItem());
        }
            
            
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnRegistrarVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarVentaActionPerformed

        
        calcularImporte();
       
        
        for (int i = 0; i < tablaArticulos.getRowCount() ; i++) {
            
            System.out.println(tablaArticulos.getValueAt(i,3).getClass());
            
            int noPiezas = 0;
            if(tablaArticulos.getValueAt(i,3).getClass()==String.class){
            
                noPiezas = Integer.parseInt((String) tablaArticulos.getValueAt(i,3));
            }else
                noPiezas = (int)tablaArticulos.getValueAt(i,3);
            
            
            unaInterfazDeVentas.registrarDetalleDeVenta(lblTienda.getText(),
                    Integer.parseInt(lblIdVenta.getText()),
                    Integer.parseInt(lblAnio.getText()),Integer.parseInt(lblTrimestre.getText()),(String)tablaArticulos.getValueAt(i,0),
                    (String)tablaArticulos.getValueAt(i,1),
                    noPiezas);
            
            unaInterfazDeVentas.actualizarExistencias(lblTienda.getText(), (String)tablaArticulos.getValueAt(i,0),
                    (String)tablaArticulos.getValueAt(i,1),noPiezas);
           
        }
        unaInterfazDeVentas.registrarEmpleadoTieneVentas(lblCURP.getText(), Integer.parseInt(lblIdVenta.getText()),
                Integer.parseInt(lblAnio.getText()),Integer.parseInt(lblTrimestre.getText()));
        
        
        unaInterfazDeVentas.registrarRecordDeVentas((String)lblTienda.getText(), Integer.parseInt(lblIdVenta.getText()),Integer.parseInt(lblAnio.getText()),
                Integer.parseInt(lblTrimestre.getText()), Double.parseDouble(lblImporte.getText()));
        
        
        
        modeloTablaDeBusqueda.setRowCount(0);
        modeloTablaDeCompra.setRowCount(0);
        
               
        lblIdVenta.setText( String.valueOf(unaInterfazDeVentas.calcularIdVenta(lblTienda.getText(), Integer.parseInt(lblAnio.getText()),
                Integer.parseInt(lblTrimestre.getText()))) ); 
        
    }//GEN-LAST:event_btnRegistrarVentaActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void comboCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboCategoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboCategoriaActionPerformed

    private void rbBuscarEnOtrasTiendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbBuscarEnOtrasTiendasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbBuscarEnOtrasTiendasActionPerformed

    private void tablaBusquedaArticulosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaBusquedaArticulosMouseClicked

        
        int i = tablaBusquedaArticulos.getSelectedRow();
        
        Object [] elementos = new Object[5];
        
        elementos[0] = tablaBusquedaArticulos.getValueAt(i, 0);
        elementos[1] = tablaBusquedaArticulos.getValueAt(i, 2);
        elementos[2] = tablaBusquedaArticulos.getValueAt(i, 3);
        elementos[3] = 1;
        elementos[4] = tablaBusquedaArticulos.getValueAt(i, 4);
        
        if(busquedaEnTablaArticulos(elementos))
            modeloTablaDeCompra.addRow(elementos);
        calcularImporte();

        
        
    }//GEN-LAST:event_tablaBusquedaArticulosMouseClicked

    private void tablaArticulosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaArticulosMouseClicked

 
        
    }//GEN-LAST:event_tablaArticulosMouseClicked

    private void tablaArticulosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaArticulosMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_tablaArticulosMousePressed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        int i = tablaArticulos.getSelectedRow();
        modeloTablaDeCompra.removeRow(i);
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void jScrollPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jScrollPane1MouseClicked

    private void tablaArticulosInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_tablaArticulosInputMethodTextChanged
        System.out.println("CAMBIO!!");
    }//GEN-LAST:event_tablaArticulosInputMethodTextChanged

    private void lblImporteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImporteMouseClicked

        calcularImporte();
    }//GEN-LAST:event_lblImporteMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PanelVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PanelVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PanelVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PanelVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PanelVentas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnRegistrarVenta;
    private javax.swing.JComboBox<String> comboCategoria;
    private javax.swing.JComboBox<String> comboProveedor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblAnio;
    private javax.swing.JLabel lblCURP;
    private javax.swing.JLabel lblIdVenta;
    private javax.swing.JLabel lblImporte;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblTienda;
    private javax.swing.JLabel lblTrimestre;
    private javax.swing.JRadioButton rbBuscarEnOtrasTiendas;
    private javax.swing.JRadioButton rbCategoria;
    private javax.swing.JRadioButton rbNombre;
    private javax.swing.JRadioButton rbProveedor;
    private javax.swing.JTable tablaArticulos;
    private javax.swing.JTable tablaBusquedaArticulos;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables

        
    public void actualizarTabla(List<Object[]> articulos){
        
        modeloTablaDeBusqueda.setRowCount(0);
			
	Object[] registro = new Object[5];
            if (articulos!=null) {
                	
                for(int i=0;i<articulos.size();i++){
			
                        registro = articulos.get(i);
			modeloTablaDeBusqueda.addRow(registro);	
		}
		tablaBusquedaArticulos.setModel(modeloTablaDeBusqueda);
            }else
                JOptionPane.showMessageDialog(null, "NO SE ENCONTRO EL ARTICULO");
		

		
        
    }
    
        
    public void cargarComboCategoria(List<Categoria> categorias){
        
        comboCategoria.removeAllItems();
        for (int i = 0; i < categorias.size(); i++) {
            
            comboCategoria.addItem(categorias.get(i).getCategoria());
            
        }
        
    }
    
        public void cargarComboProveedores(List<Proveedor> proveedores){
        
        comboProveedor.removeAllItems();
        
        for (int i = 0; i < proveedores.size(); i++) {
            
            
            comboProveedor.addItem(proveedores.get(i).getNombre());
            
        }
        
    }
        
    public boolean busquedaEnTablaArticulos(Object[] articulo){
        
                
        for (int j = 0; j < tablaArticulos.getRowCount(); j++) {
            
            if(articulo[0]==tablaArticulos.getValueAt(j, 0)&&articulo[1]==tablaArticulos.getValueAt(j, 1))
                return false;
            
                        
        }
        return true;
    }
    
    public void calcularImporte(){
        
                
        float importe = 0;
        int i = tablaArticulos.getSelectedRow();            

        
        
        try {
            
            
            System.out.println("JAJAJAJAJAJA");
            for (int j = 0; j < tablaArticulos.getRowCount(); j++) {
                
                int noPiezas = 0;
                
                if(tablaArticulos.getValueAt(j,3).getClass()==String.class){
                    noPiezas = Integer.parseInt((String) tablaArticulos.getValueAt(j,3));
                }else
                    noPiezas = (int)tablaArticulos.getValueAt(j,3);
                
                if(noPiezas>(int)tablaArticulos.getValueAt(j, 4))
                   tablaArticulos.setValueAt(tablaArticulos.getValueAt(j, 4), j, 3);
                importe += noPiezas* (float)tablaArticulos.getValueAt(j, 2);
                
            }
        
        lblImporte.setText(String.valueOf(importe));
        } catch (Exception e) {
            
            JOptionPane.showMessageDialog(null, "INGRESE UNA CANTIDAD");
        }
        
    }
    
    

}
