/*
 * This java source file is generated by DAO4J v1.19
 * Generated on Tue Mar 06 02:03:08 CST 2018
 * For more information, please contact b-i-d@163.com
 * Please check http://sourceforge.net/projects/dao4j/ for the latest version.
 */

package dao4j.sample.orm;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.SQLException;
import java.sql.Types;
import java.util.List;
import java.util.ArrayList;
import dao4j.sample.*;
import dao4j.sample.dao.TiempoDAO;

/**
 * This class provides methods to populate DB Table of Tiempo
 */
public class TiempoDAOImpl implements TiempoDAO {
    /* SQL to insert data */
    private static final String SQL_INSERT =
        "INSERT INTO Tiempo ("
        + "hora"
        + ") VALUES (?)";

    /* SQL to select data */
    private static final String SQL_SELECT =
        "SELECT "
        + "hora "
        + "FROM Tiempo WHERE "
        + "hora = ?";

    /* SQL to update data */
    private static final String SQL_UPDATE =
        "UPDATE Tiempo SET "
        + "WHERE "
        + "hora = ?";

    /* SQL to delete data */
    private static final String SQL_DELETE =
        "DELETE FROM Tiempo WHERE "
        + "hora = ?";

    /**
     * Create a new record in Database.
     * @param bean   The Object to be inserted.
     * @param conn   JDBC Connection.
     * @exception    SQLException if something is wrong.
     */
    public void create(Tiempo bean, Connection conn) throws SQLException {
        PreparedStatement ps = null;
        try {
            ps = conn.prepareStatement(SQL_INSERT);
            if (bean.getHora() != null)
                ps.setDate(1, new java.sql.Date(bean.getHora().getTime()));
            else
                ps.setNull(1, Types.DATE);
            ps.executeUpdate();
        }finally {
            close(ps);
        }
    }

    /**
     * Retrive a record from Database.
     * @param beanKey   The PK Object to be retrived.
     * @param conn      JDBC Connection.
     * @exception       SQLException if something is wrong.
     */
    public Tiempo load(TiempoKey key, Connection conn) throws SQLException {
        PreparedStatement ps = null;
        ResultSet rs = null;
        try {
            ps = conn.prepareStatement(SQL_SELECT);
            if (key.getHora() != null)
                ps.setDate(1, new java.sql.Date(key.getHora().getTime()));
            else
                ps.setNull(1, Types.DATE);
            rs = ps.executeQuery();
            List results = getResults(rs);
            if (results.size() > 0)
                return (Tiempo) results.get(0);
            else
                return null;
        }finally {
            close(rs);
            close(ps);
        }
    }

    /**
     * Update a record in Database.
     * @param bean   The Object to be saved.
     * @param conn   JDBC Connection.
     * @exception    SQLException if something is wrong.
     */
    public void update(Tiempo bean, Connection conn) throws SQLException {
        PreparedStatement ps = null;
        try {
            ps = conn.prepareStatement(SQL_UPDATE);
            if (bean.getHora() != null)
                ps.setDate(1, new java.sql.Date(bean.getHora().getTime()));
            else
                ps.setNull(1, Types.DATE);
            ps.executeUpdate();
        }finally {
            close(ps);
        }
    }

    /**
     * Create a new record in Database.
     * @param bean   The PK Object to be deleted.
     * @param conn   JDBC Connection.
     * @exception    SQLException if something is wrong.
     */
    public void delete(TiempoKey key, Connection conn) throws SQLException {
        PreparedStatement ps = null;
        try {
            ps = conn.prepareStatement(SQL_DELETE);
            if (key.getHora() != null)
                ps.setDate(1, new java.sql.Date(key.getHora().getTime()));
            else
                ps.setDate(1, null);
            ps.executeUpdate();
        }finally {
            close(ps);
        }
    }
    
    /**
     * Populate the ResultSet.
     * @param rs     The ResultSet.
     * @return       The Object to retrieve from DB.
     * @exception    SQLException if something is wrong.
     */
    protected List<Tiempo> getResults(ResultSet rs) throws SQLException {
        List results = new ArrayList<Tiempo>();
        while (rs.next()) {
            Tiempo bean = new Tiempo();
            bean.setHora(rs.getDate("hora"));
            results.add(bean);
        }
        return results;
    }

    /**
     * Close JDBC Statement.
     * @param stmt  Statement to be closed.
     */
    protected void close(Statement stmt) {
        if (stmt != null) {
            try {
                stmt.close();
            }catch(SQLException e){}
        }
    }

    /**
     * Close JDBC ResultSet.
     * @param rs  ResultSet to be closed.
     */
    protected void close(ResultSet rs) {
        if (rs != null) {
            try {
                rs.close();
            }catch(SQLException e){}
        }
    }
}