/*
 * This java source file is generated by DAO4J v1.19
 * Generated on Fri Mar 09 06:40:53 CST 2018
 * For more information, please contact b-i-d@163.com
 * Please check http://sourceforge.net/projects/dao4j/ for the latest version.
 */

package DAOimpl;

import modelo.Categoriausuario;
import modelo.CategoriausuarioKey;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.SQLException;
import java.sql.Types;
import java.util.List;
import java.util.ArrayList;
import DAO.CategoriausuarioDAO;

/**
 * This class provides methods to populate DB Table of CategoriaUsuario
 */
public class CategoriausuarioDAOImpl implements CategoriausuarioDAO {
    /* SQL to insert data */
    private static final String SQL_INSERT =
        "INSERT INTO CategoriaUsuario ("
        + "categoria"
        + ") VALUES (?)";

    /* SQL to select data */
    
    private static final String SQL_SELECT_ALL =
        "SELECT "
        + "categoria "
        + "FROM CategoriaUsuario";
    
    private static final String SQL_SELECT =
        "SELECT "
        + "categoria "
        + "FROM CategoriaUsuario WHERE "
        + "categoria = ?";

    /* SQL to update data */
    private static final String SQL_UPDATE =
        "UPDATE CategoriaUsuario SET "
        + "WHERE "
        + "categoria = ?";

    /* SQL to delete data */
    private static final String SQL_DELETE =
        "DELETE FROM CategoriaUsuario WHERE "
        + "categoria = ?";

    /**
     * Create a new record in Database.
     * @param bean   The Object to be inserted.
     * @param conn   JDBC Connection.
     * @exception    SQLException if something is wrong.
     */
    public void create(Categoriausuario bean, Connection conn) throws SQLException {
        PreparedStatement ps = null;
        try {
            ps = conn.prepareStatement(SQL_INSERT);
            ps.setString(1, bean.getCategoria());
            ps.executeUpdate();
        }finally {
            close(ps);
        }
    }

    /**
     * Retrive a record from Database.
     * @param beanKey   The PK Object to be retrived.
     * @param conn      JDBC Connection.
     * @exception       SQLException if something is wrong.
     */
    
        
    public List<Object[]>loadCategorias(Connection conn) throws SQLException {
        PreparedStatement ps = null;
        ResultSet rs = null;
        try {
            ps = conn.prepareStatement(SQL_SELECT_ALL);
            
            rs = ps.executeQuery();
            List results = getResultsOfCategoria(rs);
            if (results.size() > 0)
                return results;
            else
                return null;
        }finally {
            close(rs);
            close(ps);
        }
    }
    
    public Categoriausuario load(CategoriausuarioKey key, Connection conn) throws SQLException {
        PreparedStatement ps = null;
        ResultSet rs = null;
        try {
            ps = conn.prepareStatement(SQL_SELECT);
            ps.setString(1, key.getCategoria());
            rs = ps.executeQuery();
            List results = getResults(rs);
            if (results.size() > 0)
                return (Categoriausuario) results.get(0);
            else
                return null;
        }finally {
            close(rs);
            close(ps);
        }
    }

    /**
     * Update a record in Database.
     * @param bean   The Object to be saved.
     * @param conn   JDBC Connection.
     * @exception    SQLException if something is wrong.
     */
    public void update(Categoriausuario bean, Connection conn) throws SQLException {
        PreparedStatement ps = null;
        try {
            ps = conn.prepareStatement(SQL_UPDATE);
            ps.setString(1, bean.getCategoria());
            ps.executeUpdate();
        }finally {
            close(ps);
        }
    }

    /**
     * Create a new record in Database.
     * @param bean   The PK Object to be deleted.
     * @param conn   JDBC Connection.
     * @exception    SQLException if something is wrong.
     */
    public void delete(CategoriausuarioKey key, Connection conn) throws SQLException {
        PreparedStatement ps = null;
        try {
            ps = conn.prepareStatement(SQL_DELETE);
            ps.setString(1, key.getCategoria());
            ps.executeUpdate();
        }finally {
            close(ps);
        }
    }
    
    /**
     * Populate the ResultSet.
     * @param rs     The ResultSet.
     * @return       The Object to retrieve from DB.
     * @exception    SQLException if something is wrong.
     */
    
        
    protected List<Object[]> getResultsOfCategoria(ResultSet rs) throws SQLException {
        List results = new ArrayList<Object[]>();
        while (rs.next()) {
            Object registro;
            registro = (rs.getString("categoria"));
            System.out.println(registro);
            results.add(registro);
        }
        return results;
    }
    
    protected List<Categoriausuario> getResults(ResultSet rs) throws SQLException {
        List results = new ArrayList<Categoriausuario>();
        while (rs.next()) {
            Categoriausuario bean = new Categoriausuario();
            bean.setCategoria(rs.getString("categoria"));
            results.add(bean);
        }
        return results;
    }

    /**
     * Close JDBC Statement.
     * @param stmt  Statement to be closed.
     */
    protected void close(Statement stmt) {
        if (stmt != null) {
            try {
                stmt.close();
            }catch(SQLException e){}
        }
    }

    /**
     * Close JDBC ResultSet.
     * @param rs  ResultSet to be closed.
     */
    protected void close(ResultSet rs) {
        if (rs != null) {
            try {
                rs.close();
            }catch(SQLException e){}
        }
    }
}