/*
 * This java source file is generated by DAO4J v1.19
 * Generated on Sun Feb 25 05:11:23 CST 2018
 * For more information, please contact b-i-d@163.com
 * Please check http://sourceforge.net/projects/dao4j/ for the latest version.
 */

package DAOimpl;

import modelo.EmpleadoKey;
import modelo.Empleado;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.SQLException;
import java.sql.Types;
import java.util.List;
import java.util.ArrayList;
import DAO.EmpleadoDAO;

/**
 * This class provides methods to populate DB Table of Empleado
 */
public class EmpleadoDAOImpl implements EmpleadoDAO {
    /* SQL to insert data */
    private static final String SQL_INSERT =
        "INSERT INTO Empleado ("
        + "CURP, idTienda"
        + ") VALUES (?, ?)";

    /* SQL to select data */
    private static final String SQL_SELECT =
        "SELECT "
        + "CURP, puesto, idTienda "
        + "FROM Empleado WHERE "
        + "CURP = ? AND idTienda = ?";
    
        private static final String SQL_SELECT_BY_CURP =
        "SELECT "
        + "CURP, idTienda "
        + "FROM Empleado WHERE "
        + "CURP = ?";

    /* SQL to update data */
    private static final String SQL_UPDATE =
        "UPDATE Empleado SET "
        + ""
        + "WHERE "
        + "CURP = ? AND idTienda = ?";

    /* SQL to delete data */
    private static final String SQL_DELETE =
        "DELETE FROM Empleado WHERE "
        + "CURP = ? AND idTienda = ?";

    /**
     * Create a new record in Database.
     * @param bean   The Object to be inserted.
     * @param conn   JDBC Connection.
     * @exception    SQLException if something is wrong.
     */
    public void create(Empleado bean, Connection conn) throws SQLException {
        PreparedStatement ps = null;
        try {
            ps = conn.prepareStatement(SQL_INSERT);
            ps.setString(1, bean.getCurp());
            
            ps.setString(2, bean.getIdtienda());
            System.out.println("-----------------INSERSION DE EMPLEADO DESDE EL DAO "+ps);
            ps.executeUpdate();
        }finally {
            close(ps);
        }
    }

    /**
     * Retrive a record from Database.
     * @param beanKey   The PK Object to be retrived.
     * @param conn      JDBC Connection.
     * @exception       SQLException if something is wrong.
     */
    
       
    public Empleado loadEmpleado(String  CURP, Connection conn) throws SQLException {
        PreparedStatement ps = null;
        ResultSet rs = null;
        try {
            ps = conn.prepareStatement(SQL_SELECT_BY_CURP);
            ps.setString(1, CURP);
            System.out.println("EL PS DESDE EL DAO "+ps);
            
            rs = ps.executeQuery();
            List results = getResults(rs);
            if (results.size() > 0)
                return (Empleado) results.get(0);
            else
                return null;
        }finally {
            close(rs);
            close(ps);
        }
    }

    
    public Empleado load(EmpleadoKey key, Connection conn) throws SQLException {
        PreparedStatement ps = null;
        ResultSet rs = null;
        try {
            ps = conn.prepareStatement(SQL_SELECT);
            ps.setString(1, key.getCurp());
            ps.setString(2, key.getIdtienda());
            rs = ps.executeQuery();
            List results = getResults(rs);
            if (results.size() > 0)
                return (Empleado) results.get(0);
            else
                return null;
        }finally {
            close(rs);
            close(ps);
        }
    }

    /**
     * Update a record in Database.
     * @param bean   The Object to be saved.
     * @param conn   JDBC Connection.
     * @exception    SQLException if something is wrong.
     */
    public void update(Empleado bean, Connection conn) throws SQLException {
        PreparedStatement ps = null;
        try {
            ps = conn.prepareStatement(SQL_UPDATE);
            ps.setString(1, bean.getPuesto());
            ps.setString(2, bean.getCurp());
            ps.setString(3, bean.getIdtienda());
            ps.executeUpdate();
        }finally {
            close(ps);
        }
    }

    /**
     * Create a new record in Database.
     * @param bean   The PK Object to be deleted.
     * @param conn   JDBC Connection.
     * @exception    SQLException if something is wrong.
     */
    public void delete(EmpleadoKey key, Connection conn) throws SQLException {
        PreparedStatement ps = null;
        try {
            ps = conn.prepareStatement(SQL_DELETE);
            ps.setString(1, key.getCurp());
            ps.setString(2, key.getIdtienda());
            ps.executeUpdate();
        }finally {
            close(ps);
        }
    }
    
    /**
     * Populate the ResultSet.
     * @param rs     The ResultSet.
     * @return       The Object to retrieve from DB.
     * @exception    SQLException if something is wrong.
     */
    protected List<Empleado> getResults(ResultSet rs) throws SQLException {
        List results = new ArrayList<Empleado>();
        while (rs.next()) {
            System.out.println("SI HAY");
            Empleado bean = new Empleado();
            bean.setCurp(rs.getString("CURP"));
            
            bean.setIdtienda(rs.getString("idTienda"));
            System.out.println("EL EMPLEADO DESDE EL DAO "+ bean.toString());
            results.add(bean);
        }
        return results;
    }

    /**
     * Close JDBC Statement.
     * @param stmt  Statement to be closed.
     */
    protected void close(Statement stmt) {
        if (stmt != null) {
            try {
                stmt.close();
            }catch(SQLException e){}
        }
    }

    /**
     * Close JDBC ResultSet.
     * @param rs  ResultSet to be closed.
     */
    protected void close(ResultSet rs) {
        if (rs != null) {
            try {
                rs.close();
            }catch(SQLException e){}
        }
    }
}