/*
 * This java source file is generated by DAO4J v1.19
 * Generated on Mon Mar 05 21:04:16 CST 2018
 * For more information, please contact b-i-d@163.com
 * Please check http://sourceforge.net/projects/dao4j/ for the latest version.
 */

package DAOimpl;

import modelo.PartidoKey;
import modelo.Partido;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.SQLException;
import java.sql.Types;
import java.util.List;
import java.util.ArrayList;
import DAO.PartidoDAO;
import java.text.SimpleDateFormat;
import java.util.Date;

/**
 * This class provides methods to populate DB Table of Partido
 */
public class PartidoDAOImpl implements PartidoDAO {
    /* SQL to insert data */
    private static final String SQL_INSERT =
        "INSERT INTO Partido ("
        + "temporada, noJornada, equipoLocal, equipoVisitante, fecha, hora, marcadorLocal, "
        + "marcadorVisitante"
        + ") VALUES (?, ?, ?, ?, ?, ?, ?, ?)";

    /* SQL to select data */
    private static final String SQL_SELECT_ALL=
            "SELECT"
            + "* FROM Partido";
    
    private static final String SQL_SELECT =
        "SELECT "
        + "temporada, noJornada, equipoLocal, equipoVisitante, fecha, hora, marcadorLocal, "
        + "marcadorVisitante "
        + "FROM Partido WHERE "
        + "temporada = ? AND noJornada = ? AND equipoLocal = ? AND equipoVisitante = ?";

    /* SQL to update data */
    private static final String SQL_UPDATE =
        "UPDATE Partido SET "
        + "fecha = ?, hora = ?, marcadorLocal = ?, marcadorVisitante = ? "
        + "WHERE "
        + "temporada = ? AND noJornada = ? AND equipoLocal = ? AND equipoVisitante = ?";

    /* SQL to delete data */
    private static final String SQL_DELETE =
        "DELETE FROM Partido WHERE "
        + "temporada = ? AND noJornada = ? AND equipoLocal = ? AND equipoVisitante = ?";

    /**
     * Create a new record in Database.
     * @param bean   The Object to be inserted.
     * @param conn   JDBC Connection.
     * @exception    SQLException if something is wrong.
     */
    public void create(Partido bean, Connection conn) throws SQLException {
        PreparedStatement ps = null;
        try {
            
                       
            SimpleDateFormat hcn = new SimpleDateFormat("hh:mm");
           
            String laHora = hcn.format(bean.getHora());
            System.out.println("HORA DESDE EL DAOIMPL PARTIDO "+laHora);
            
            
            ps = conn.prepareStatement(SQL_INSERT);
            ps.setString(1, bean.getTemporada());
            ps.setInt(2, bean.getNojornada());
            ps.setString(3, bean.getEquipolocal());
            ps.setString(4, bean.getEquipovisitante());
            if (bean.getFecha() != null)
                ps.setDate(5, new java.sql.Date(bean.getFecha().getTime()));
            else
                ps.setNull(5, Types.DATE);
            ps.setString(6, laHora);
            ps.setInt(7, bean.getMarcadorlocal());
            ps.setInt(8, bean.getMarcadorvisitante());
            ps.executeUpdate();
        }finally {
            close(ps);
        }
    }

    /**
     * Retrive a record from Database.
     * @param beanKey   The PK Object to be retrived.
     * @param conn      JDBC Connection.
     * @exception       SQLException if something is wrong.
     */
        
    public List<Partido> load(Connection conn) throws SQLException {
        PreparedStatement ps = null;
        ResultSet rs = null;
        try {
            ps = conn.prepareStatement(SQL_SELECT_ALL);

            rs = ps.executeQuery();
            List results = getResults(rs);
            if (results.size() > 0)
                return results;
            else
                return null;
        }finally {
            close(rs);
            close(ps);
        }
    }
    
    public Partido load(PartidoKey key, Connection conn) throws SQLException {
        PreparedStatement ps = null;
        ResultSet rs = null;
        try {
            ps = conn.prepareStatement(SQL_SELECT);
            ps.setString(1, key.getTemporada());
            ps.setInt(2, key.getNojornada());
            ps.setString(3, key.getEquipolocal());
            ps.setString(4, key.getEquipovisitante());
            rs = ps.executeQuery();
            List results = getResults(rs);
            if (results.size() > 0)
                return (Partido) results.get(0);
            else
                return null;
        }finally {
            close(rs);
            close(ps);
        }
    }

    /**
     * Update a record in Database.
     * @param bean   The Object to be saved.
     * @param conn   JDBC Connection.
     * @exception    SQLException if something is wrong.
     */
    public void update(Partido bean, Connection conn) throws SQLException {
        PreparedStatement ps = null;
        try {
            
            /*laHora es una variable para insertar la hora seleccionada 
            como String
            */
            
                        
            SimpleDateFormat hcn = new SimpleDateFormat("hh:mm");
            String laHora = hcn.format(bean.getHora());
            
            ps = conn.prepareStatement(SQL_UPDATE);
            if (bean.getFecha() != null)
                ps.setDate(1, new java.sql.Date(bean.getFecha().getTime()));
            else
                ps.setNull(1, Types.DATE);

             
            ps.setString(2, laHora);
            ps.setInt(3, bean.getMarcadorlocal());
            ps.setInt(4, bean.getMarcadorvisitante());
            ps.setString(5, bean.getTemporada());
            ps.setInt(6, bean.getNojornada());
            ps.setString(7, bean.getEquipolocal());
            ps.setString(8, bean.getEquipovisitante());
            ps.executeUpdate();
        }finally {
            close(ps);
        }
    }

    /**
     * Create a new record in Database.
     * @param bean   The PK Object to be deleted.
     * @param conn   JDBC Connection.
     * @exception    SQLException if something is wrong.
     */
    public void delete(PartidoKey key, Connection conn) throws SQLException {
        PreparedStatement ps = null;
        try {
            ps = conn.prepareStatement(SQL_DELETE);
            ps.setString(1, key.getTemporada());
            ps.setInt(2, key.getNojornada());
            ps.setString(3, key.getEquipolocal());
            ps.setString(4, key.getEquipovisitante());
            ps.executeUpdate();
        }finally {
            close(ps);
        }
    }
    
    /**
     * Populate the ResultSet.
     * @param rs     The ResultSet.
     * @return       The Object to retrieve from DB.
     * @exception    SQLException if something is wrong.
     */
    protected List<Partido> getResults(ResultSet rs) throws SQLException {
        List results = new ArrayList<Partido>();
        while (rs.next()) {
            Partido bean = new Partido();
            bean.setTemporada(rs.getString("temporada"));
            bean.setNojornada(rs.getInt("noJornada"));
            bean.setEquipolocal(rs.getString("equipoLocal"));
            bean.setEquipovisitante(rs.getString("equipoVisitante"));
            bean.setFecha(rs.getDate("fecha"));
            bean.setHora(rs.getTime("hora"));
            bean.setMarcadorlocal(rs.getInt("marcadorLocal"));
            bean.setMarcadorvisitante(rs.getInt("marcadorVisitante"));
            results.add(bean);
            
        SimpleDateFormat hcn = new SimpleDateFormat("hh:mm");
        
        System.out.println("LA FECHA DESDE GET RESULTS: "+bean.getHora().getTime());
            
        }
        return results;
    }

    /**
     * Close JDBC Statement.
     * @param stmt  Statement to be closed.
     */
    protected void close(Statement stmt) {
        if (stmt != null) {
            try {
                stmt.close();
            }catch(SQLException e){}
        }
    }

    /**
     * Close JDBC ResultSet.
     * @param rs  ResultSet to be closed.
     */
    protected void close(ResultSet rs) {
        if (rs != null) {
            try {
                rs.close();
            }catch(SQLException e){}
        }
    }
}