/*
 * This java source file is generated by DAO4J v1.19
 * Generated on Wed Mar 07 23:27:26 CST 2018
 * For more information, please contact b-i-d@163.com
 * Please check http://sourceforge.net/projects/dao4j/ for the latest version.
 */

package DAOimpl;

import modelo.RecorddeequipoKey;
import modelo.Recorddeequipo;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.SQLException;
import java.sql.Types;
import java.util.List;
import java.util.ArrayList;
import DAO.RecorddeequipoDAO;

/**
 * This class provides methods to populate DB Table of RecordDeEquipo
 */
public class RecorddeequipoDAOImpl implements RecorddeequipoDAO {
    /* SQL to insert data */
    private static final String SQL_INSERT =
        "INSERT INTO RecordDeEquipo ("
        + "temporada, nombreEquipo, partidosGanados, partidosPerdidos, partidosEmpatados"
        + ") VALUES (?, ?, ?, ?, ?)";

    /* SQL to select data */
    private static final String SQL_SELECT =
        "SELECT "
        + "temporada, nombreEquipo, partidosGanados, partidosPerdidos, partidosEmpatados "
        + "FROM RecordDeEquipo WHERE "
        + "temporada = ? AND nombreEquipo = ?";
    
    private static final String SQL_SELECT_TABLA_DE_POSICIONES =    
        "SELECT "
        + "temporada, nombreEquipo, partidosGanados, partidosPerdidos, partidosEmpatados "
        + "FROM RecordDeEquipo WHERE "
        + "temporada = ? "
            + "ORDER BY partidosGanados";

    /* SQL to update data */
    private static final String SQL_UPDATE =
        "UPDATE RecordDeEquipo SET "
        + "partidosGanados = ?, partidosPerdidos = ?, partidosEmpatados = ? "
        + "WHERE "
        + "temporada = ? AND nombreEquipo = ?";

    /* SQL to delete data */
    private static final String SQL_DELETE =
        "DELETE FROM RecordDeEquipo WHERE "
        + "temporada = ? AND nombreEquipo = ?";

    /**
     * Create a new record in Database.
     * @param bean   The Object to be inserted.
     * @param conn   JDBC Connection.
     * @exception    SQLException if something is wrong.
     */
    public void create(Recorddeequipo bean, Connection conn) throws SQLException {
        PreparedStatement ps = null;
        try {
            ps = conn.prepareStatement(SQL_INSERT);
            ps.setString(1, bean.getTemporada());
            ps.setString(2, bean.getNombreequipo());
            ps.setInt(3, bean.getPartidosganados());
            ps.setInt(4, bean.getPartidosperdidos());
            ps.setInt(5, bean.getPartidosempatados());
            ps.executeUpdate();
        }finally {
            close(ps);
        }
    }

    /**
     * Retrive a record from Database.
     * @param beanKey   The PK Object to be retrived.
     * @param conn      JDBC Connection.
     * @exception       SQLException if something is wrong.
     */
    
           
            
    public List<Recorddeequipo> load(String temporada, Connection conn) throws SQLException {
        PreparedStatement ps = null;
        ResultSet rs = null;
        try {
            ps = conn.prepareStatement(SQL_SELECT_TABLA_DE_POSICIONES);
            ps.setString(1, temporada);
            rs = ps.executeQuery();
            List results = getResults(rs);
            if (results.size() > 0)
                return results;
            else
                return null;
        }finally {
            close(rs);
            close(ps);
        }
    }
    public Recorddeequipo load(RecorddeequipoKey key, Connection conn) throws SQLException {
        PreparedStatement ps = null;
        ResultSet rs = null;
        try {
            ps = conn.prepareStatement(SQL_SELECT);
            ps.setString(1, key.getTemporada());
            ps.setString(2, key.getNombreequipo());
            rs = ps.executeQuery();
            List results = getResults(rs);
            if (results.size() > 0)
                return (Recorddeequipo) results.get(0);
            else
                return null;
        }finally {
            close(rs);
            close(ps);
        }
    }

    /**
     * Update a record in Database.
     * @param bean   The Object to be saved.
     * @param conn   JDBC Connection.
     * @exception    SQLException if something is wrong.
     */
    public void update(Recorddeequipo bean, Connection conn) throws SQLException {
        PreparedStatement ps = null;
        try {
            ps = conn.prepareStatement(SQL_UPDATE);
            ps.setInt(1, bean.getPartidosganados());
            ps.setInt(2, bean.getPartidosperdidos());
            ps.setInt(3, bean.getPartidosempatados());
            ps.setString(4, bean.getTemporada());
            ps.setString(5, bean.getNombreequipo());
            ps.executeUpdate();
        }finally {
            close(ps);
        }
    }

    /**
     * Create a new record in Database.
     * @param bean   The PK Object to be deleted.
     * @param conn   JDBC Connection.
     * @exception    SQLException if something is wrong.
     */
    public void delete(RecorddeequipoKey key, Connection conn) throws SQLException {
        PreparedStatement ps = null;
        try {
            ps = conn.prepareStatement(SQL_DELETE);
            ps.setString(1, key.getTemporada());
            ps.setString(2, key.getNombreequipo());
            ps.executeUpdate();
        }finally {
            close(ps);
        }
    }
    
    /**
     * Populate the ResultSet.
     * @param rs     The ResultSet.
     * @return       The Object to retrieve from DB.
     * @exception    SQLException if something is wrong.
     */
    protected List<Recorddeequipo> getResults(ResultSet rs) throws SQLException {
        List results = new ArrayList<Recorddeequipo>();
        while (rs.next()) {
            Recorddeequipo bean = new Recorddeequipo();
            bean.setTemporada(rs.getString("temporada"));
            bean.setNombreequipo(rs.getString("nombreEquipo"));
            bean.setPartidosganados(rs.getInt("partidosGanados"));
            bean.setPartidosperdidos(rs.getInt("partidosPerdidos"));
            bean.setPartidosempatados(rs.getInt("partidosEmpatados"));
            
            
            
            results.add(bean);
        }
        return results;
    }

    /**
     * Close JDBC Statement.
     * @param stmt  Statement to be closed.
     */
    protected void close(Statement stmt) {
        if (stmt != null) {
            try {
                stmt.close();
            }catch(SQLException e){}
        }
    }

    /**
     * Close JDBC ResultSet.
     * @param rs  ResultSet to be closed.
     */
    protected void close(ResultSet rs) {
        if (rs != null) {
            try {
                rs.close();
            }catch(SQLException e){}
        }
    }
}