/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista_jpanel;

import interfaces.interfazAdministrarMercancia;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import modelo.Articulo;
import modelo.Categoria;
import modelo.Jugador;
import modelo.Proveedor;


/**
 *
 * @author rosario
 */
public class PanelAdminDeMercancia extends javax.swing.JPanel {

        private interfazAdministrarMercancia unaInterfazAdministrarMercancia;
    private DefaultTableModel modelo;
    /**
     * Creates new form PanelAdminDeMercancia
     */
  public PanelAdminDeMercancia(interfazAdministrarMercancia unaInterfazAdministrarMercancia) {
        
        this.unaInterfazAdministrarMercancia = unaInterfazAdministrarMercancia;
        
        initComponents();
        modelo = (DefaultTableModel)tableroMercancia.getModel();
    }

    private PanelAdminDeMercancia() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtPrecio = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableroMercancia = new javax.swing.JTable();
        btnAgregar = new javax.swing.JButton();
        btnBorrar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        comboCategoria = new javax.swing.JComboBox<>();
        comboProveedor = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        lblNombreTienda = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtExistencias = new javax.swing.JTextField();
        comboDeTiendas = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        rbTienda = new javax.swing.JRadioButton();
        rbCategoria = new javax.swing.JRadioButton();
        rbNombre = new javax.swing.JRadioButton();
        rbProveedor = new javax.swing.JRadioButton();
        rbBuscarEnOtrasTiendas = new javax.swing.JRadioButton();
        btnVoler = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        txtNombre.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtNombre.setForeground(new java.awt.Color(153, 51, 0));
        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });

        txtPrecio.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtPrecio.setForeground(new java.awt.Color(153, 51, 0));
        txtPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrecioActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 51, 0));
        jLabel5.setText("Precio:");

        tableroMercancia.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        tableroMercancia.setForeground(new java.awt.Color(153, 51, 0));
        tableroMercancia.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "NombreProducto", "Categoria", "Proveedor", "Precio", "Existencias"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableroMercancia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableroMercanciaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableroMercancia);

        btnAgregar.setBackground(new java.awt.Color(153, 51, 0));
        btnAgregar.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        btnAgregar.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnBorrar.setBackground(new java.awt.Color(153, 51, 0));
        btnBorrar.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        btnBorrar.setForeground(new java.awt.Color(255, 255, 255));
        btnBorrar.setText("Borrar");
        btnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarActionPerformed(evt);
            }
        });

        btnActualizar.setBackground(new java.awt.Color(153, 51, 0));
        btnActualizar.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        btnActualizar.setForeground(new java.awt.Color(255, 255, 255));
        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        comboCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        comboProveedor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel7.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(153, 51, 0));
        jLabel7.setText("Existencias");

        txtExistencias.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtExistencias.setForeground(new java.awt.Color(153, 51, 0));
        txtExistencias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtExistenciasActionPerformed(evt);
            }
        });

        comboDeTiendas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButton1.setText("Cargar Productos");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        rbTienda.setText("Tienda");
        rbTienda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbTiendaActionPerformed(evt);
            }
        });

        rbCategoria.setText("Categoria");

        rbNombre.setText("Nombre");

        rbProveedor.setText("Proveedor");

        rbBuscarEnOtrasTiendas.setText("Buscar e otras tienda");

        btnVoler.setText("Volver");
        btnVoler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(rbTienda))
                        .addGap(239, 239, 239)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(834, 834, 834))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btnAgregar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnBorrar)
                                .addGap(18, 18, 18)
                                .addComponent(btnActualizar))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(rbCategoria)
                                    .addComponent(rbNombre)
                                    .addComponent(rbProveedor))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(comboDeTiendas, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(comboCategoria, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtExistencias)
                                        .addComponent(txtPrecio)
                                        .addComponent(txtNombre)
                                        .addComponent(comboProveedor, 0, 190, Short.MAX_VALUE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblNombreTienda, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(928, 928, 928))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(rbBuscarEnOtrasTiendas)
                                .addGap(198, 198, 198)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 486, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(39, 39, 39)
                                        .addComponent(btnVoler))
                                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(39, 39, 39)
                .addComponent(jLabel2)
                .addGap(3, 3, 3)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboDeTiendas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(rbTienda))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNombreTienda)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(comboCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(rbCategoria))
                                .addGap(16, 16, 16)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(rbNombre))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(comboProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(rbProveedor)))))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtExistencias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addComponent(rbBuscarEnOtrasTiendas)
                        .addGap(26, 26, 26)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAgregar)
                            .addComponent(btnBorrar)
                            .addComponent(btnActualizar)))
                    .addComponent(btnVoler))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 996, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void txtPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrecioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecioActionPerformed

    private void tableroMercanciaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableroMercanciaMouseClicked

        int i = tableroMercancia.getSelectedRow();

        txtNombre.setText((String)tableroMercancia.getValueAt(i,0));
        comboCategoria.setSelectedItem((String)tableroMercancia.getValueAt(i,1));
        comboProveedor.setSelectedItem((String)tableroMercancia.getValueAt(i,2));
        txtPrecio.setText(String.valueOf( tableroMercancia.getValueAt(i,3)));
        txtExistencias.setText(String.valueOf( tableroMercancia.getValueAt(i,4)));

    }//GEN-LAST:event_tableroMercanciaMouseClicked

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed

        unaInterfazAdministrarMercancia.agregar((String)comboCategoria.getSelectedItem(),(String)comboProveedor.getSelectedItem(),
            txtNombre.getText(), Double.parseDouble(txtPrecio.getText()),String.valueOf(comboDeTiendas.getSelectedItem()),Integer.parseInt(txtExistencias.getText()));
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed

        unaInterfazAdministrarMercancia.borrar((String)comboProveedor.getSelectedItem(),txtNombre.getText(),String.valueOf(comboDeTiendas.getSelectedItem()));

    }//GEN-LAST:event_btnBorrarActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed

        unaInterfazAdministrarMercancia.actualizar((String)comboCategoria.getSelectedItem(),(String)comboProveedor.getSelectedItem(),
            txtNombre.getText(), Double.parseDouble(txtPrecio.getText()),String.valueOf(comboDeTiendas.getSelectedItem()),Integer.parseInt(txtExistencias.getText()));

    }//GEN-LAST:event_btnActualizarActionPerformed

    private void txtExistenciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtExistenciasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtExistenciasActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

                
        int tipoBusqueda;
        if(!rbBuscarEnOtrasTiendas.isSelected()&&rbNombre.isSelected()&&rbProveedor.isSelected()&&!rbCategoria.isSelected()){
            unaInterfazAdministrarMercancia.buscarProducto(String.valueOf(comboDeTiendas.getSelectedItem()), txtNombre.getText(), (String) comboProveedor.getSelectedItem(), 1);
        }else if(!rbBuscarEnOtrasTiendas.isSelected()&&rbNombre.isSelected()&&!rbProveedor.isSelected()&&!rbCategoria.isSelected()){
            unaInterfazAdministrarMercancia.buscarProducto(String.valueOf(comboDeTiendas.getSelectedItem()), txtNombre.getText(), 1);
        }else if(!rbBuscarEnOtrasTiendas.isSelected()&&!rbNombre.isSelected()&&rbProveedor.isSelected()&&!rbCategoria.isSelected()){
            unaInterfazAdministrarMercancia.buscarProducto(String.valueOf(comboDeTiendas.getSelectedItem()), (String)comboProveedor.getSelectedItem(), 2);
        }else if(!rbBuscarEnOtrasTiendas.isSelected()&&!rbNombre.isSelected()&&!rbProveedor.isSelected()&&rbCategoria.isSelected()){
            unaInterfazAdministrarMercancia.buscarProducto(String.valueOf(comboDeTiendas.getSelectedItem()), (String)comboCategoria.getSelectedItem(), 3);
        }else if(rbBuscarEnOtrasTiendas.isSelected()&&rbNombre.isSelected()&&rbProveedor.isSelected()&&!rbCategoria.isSelected()){
            unaInterfazAdministrarMercancia.buscarProductoEnTodasLasTiendas(txtNombre.getText(), (String) comboProveedor.getSelectedItem());
        }
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void rbTiendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbTiendaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbTiendaActionPerformed

    private void btnVolerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolerActionPerformed

        unaInterfazAdministrarMercancia.regresar();
        
    }//GEN-LAST:event_btnVolerActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnVoler;
    private javax.swing.JComboBox<String> comboCategoria;
    private javax.swing.JComboBox<String> comboDeTiendas;
    private javax.swing.JComboBox<String> comboProveedor;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblNombreTienda;
    private javax.swing.JRadioButton rbBuscarEnOtrasTiendas;
    private javax.swing.JRadioButton rbCategoria;
    private javax.swing.JRadioButton rbNombre;
    private javax.swing.JRadioButton rbProveedor;
    private javax.swing.JRadioButton rbTienda;
    private javax.swing.JTable tableroMercancia;
    private javax.swing.JTextField txtExistencias;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPrecio;
    // End of variables declaration//GEN-END:variables
public void actualizarTabla(List<Object[]> articulos){
        
        modelo.setRowCount(0);
			
	Object[] registro = new Object[5];
            if (articulos==null) {
                System.out.println("COCK SUCKER!!");
            }
		
	for(int i=0;i<articulos.size();i++){
			
                        registro = articulos.get(i);
                    
                        
			
			modelo.addRow(registro);
			
		}
		tableroMercancia.setModel(modelo);
		
        
    }
        
    public void cargarComboCategoria(List<Categoria> categorias){
        
        comboCategoria.removeAllItems();
        for (int i = 0; i < categorias.size(); i++) {
            
            comboCategoria.addItem(categorias.get(i).getCategoria());
            
        }
        
    }
    
    public void cargarComboProveedores(List<Proveedor> proveedores){
        
        comboProveedor.removeAllItems();
        
        for (int i = 0; i < proveedores.size(); i++) {
            
            
            comboProveedor.addItem(proveedores.get(i).getNombre());
            
        }
        
    }
    
    public String getNombreTienda(){
        
        return String.valueOf(comboDeTiendas.getSelectedItem());
    }
    
    
        
    public void cargarComboDeTiendas(List<Object[]> registros){
        comboDeTiendas.removeAllItems();
        
        for (int i = 0; i<registros.size() ; i++) {
            
            comboDeTiendas.addItem(String.valueOf(registros.get(i)));

        }
        
        
        
    }

}
