/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista_jpanel;

import interfaces.InterfazTableroDeMercado;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import modelo.Partido;

/**
 *
 * @author rosario
 */
public class PanelTableroDeMercado extends javax.swing.JPanel {

        
    InterfazTableroDeMercado unaInterfazTableroDeMercado;
    private DefaultTableModel modeloTablaDeVentas;
    private DefaultTableModel modeloTablaDeVendedores;
    
    

    /**
     * Creates new form tablero_mercado
     */
    public PanelTableroDeMercado(InterfazTableroDeMercado unaInterfazTableroDeMercado) {
        
        initComponents();
        
        this.unaInterfazTableroDeMercado = unaInterfazTableroDeMercado;
        initComponents();
        
        modeloTablaDeVentas = (DefaultTableModel)tablaDeVentas.getModel();
        modeloTablaDeVendedores = (DefaultTableModel)tablaDeVendedores.getModel();
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaDeVentas = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaDeVendedores = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        rbTienda = new javax.swing.JRadioButton();
        rbAnio = new javax.swing.JRadioButton();
        rbTrimestre = new javax.swing.JRadioButton();
        txtAnio = new javax.swing.JTextField();
        txtTrimestre = new javax.swing.JTextField();
        comboDeTiendas = new javax.swing.JComboBox<>();
        btnFiltroVendedores = new javax.swing.JButton();
        btnFiltroVentas = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 51, 0));
        jLabel3.setText("Bienvenido");

        jLabel4.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 51, 0));
        jLabel4.setText("nombre");

        jLabel5.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 51, 0));
        jLabel5.setText("Ventas:");

        jLabel6.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(153, 51, 0));
        jLabel6.setText("Vendedores:");

        tablaDeVentas.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        tablaDeVentas.setForeground(new java.awt.Color(153, 51, 0));
        tablaDeVentas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "TIENDA", "ANIO", "TRIMESTRE", "VENTAS TOTALES"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablaDeVentas);

        tablaDeVendedores.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        tablaDeVendedores.setForeground(new java.awt.Color(153, 51, 0));
        tablaDeVendedores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "TIENDA", "ANIO", "TRIMESTRE", "NOMBRE", "PATERNO", "VENTAS TOTALES"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tablaDeVendedores);

        jButton4.setBackground(new java.awt.Color(153, 51, 0));
        jButton4.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Adm. usuarios");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(153, 51, 0));
        jButton5.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Salir");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        rbTienda.setText("Nombre de la tienda");

        rbAnio.setText("Anio");
        rbAnio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbAnioActionPerformed(evt);
            }
        });

        rbTrimestre.setText("Trimestre");

        txtAnio.setText("2018");
        txtAnio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAnioActionPerformed(evt);
            }
        });

        txtTrimestre.setText("1");

        comboDeTiendas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnFiltroVendedores.setText("FILTRAR RECORD DE VENDEDORES");
        btnFiltroVendedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFiltroVendedoresActionPerformed(evt);
            }
        });

        btnFiltroVentas.setText("FILTRAR RECORD DE VENTAS");
        btnFiltroVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFiltroVentasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel4)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(rbTrimestre)
                                            .addComponent(rbTienda)
                                            .addComponent(rbAnio))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtTrimestre, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                                            .addComponent(txtAnio)
                                            .addComponent(comboDeTiendas, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(55, 55, 55)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jButton4)
                                            .addComponent(jButton5)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(btnFiltroVentas, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btnFiltroVendedores, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(246, 246, 246)))))
                        .addGap(55, 55, 55))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6)
                        .addGap(505, 505, 505))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(comboDeTiendas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtAnio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rbAnio))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTrimestre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rbTrimestre)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addGap(18, 18, 18)
                                .addComponent(rbTienda))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(jLabel1)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnFiltroVentas)
                        .addGap(18, 18, 18)
                        .addComponent(btnFiltroVendedores)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(jButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton5))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void rbAnioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbAnioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbAnioActionPerformed

    private void btnFiltroVendedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFiltroVendedoresActionPerformed
        
                
        int modoDeBusqueda=0;
        if(!rbAnio.isSelected()&&!rbTienda.isSelected()&&!rbTrimestre.isSelected()){
            modoDeBusqueda = 1;
            unaInterfazTableroDeMercado.cargarTablaDeVendedores(null, 0, 0, modoDeBusqueda);
        }else if(rbAnio.isSelected()&&!rbTienda.isSelected()&&!rbTrimestre.isSelected()){
            modoDeBusqueda = 2;
            unaInterfazTableroDeMercado.cargarTablaDeVendedores(null, Integer.parseInt(txtAnio.getText()), 0, modoDeBusqueda);
        }else if(!rbAnio.isSelected()&&rbTienda.isSelected()&&!rbTrimestre.isSelected()){
            modoDeBusqueda =3;
            unaInterfazTableroDeMercado.cargarTablaDeVendedores((String)comboDeTiendas.getSelectedItem(), 0, 0, modoDeBusqueda);
        }else if(rbAnio.isSelected()&&!rbTienda.isSelected()&&rbTrimestre.isSelected()){
            modoDeBusqueda = 4;
            unaInterfazTableroDeMercado.cargarTablaDeVendedores(null, Integer.parseInt(txtAnio.getText()),
                    Integer.parseInt(txtTrimestre.getText()), modoDeBusqueda);
            
        }else if(rbAnio.isSelected()&&rbTienda.isSelected()&&rbTrimestre.isSelected()){
            modoDeBusqueda = 5;
            unaInterfazTableroDeMercado.cargarTablaDeVendedores((String)comboDeTiendas.getSelectedItem(), Integer.parseInt(txtAnio.getText()),
                    Integer.parseInt(txtTrimestre.getText()), modoDeBusqueda);
        }else if(rbAnio.isSelected()&&rbTienda.isSelected()&&!rbTrimestre.isSelected()){
            modoDeBusqueda = 6;
            unaInterfazTableroDeMercado.cargarTablaDeVendedores((String)comboDeTiendas.getSelectedItem(), Integer.parseInt(txtAnio.getText()),
                    0, modoDeBusqueda);
        }else if(!rbAnio.isSelected()&&!rbTienda.isSelected()&&rbTrimestre.isSelected()){
            modoDeBusqueda = 7;
            unaInterfazTableroDeMercado.cargarTablaDeVendedores(null, 0,
                                    Integer.parseInt(txtTrimestre.getText()), modoDeBusqueda);
        }
    }//GEN-LAST:event_btnFiltroVendedoresActionPerformed

    private void txtAnioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAnioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAnioActionPerformed

    private void btnFiltroVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFiltroVentasActionPerformed
        
        int modoDeBusqueda=0;
        if(!rbAnio.isSelected()&&!rbTienda.isSelected()&&!rbTrimestre.isSelected()){
            modoDeBusqueda = 1;
            unaInterfazTableroDeMercado.cargarTablaDeVentas(null, 0, 0, modoDeBusqueda);
        }else if(rbAnio.isSelected()&&!rbTienda.isSelected()&&!rbTrimestre.isSelected()){
            modoDeBusqueda = 2;
            unaInterfazTableroDeMercado.cargarTablaDeVentas(null, Integer.parseInt(txtAnio.getText()), 0, modoDeBusqueda);
        }else if(!rbAnio.isSelected()&&rbTienda.isSelected()&&!rbTrimestre.isSelected()){
            modoDeBusqueda =3;
            unaInterfazTableroDeMercado.cargarTablaDeVentas((String)comboDeTiendas.getSelectedItem(), 0, 0, modoDeBusqueda);
        }else if(rbAnio.isSelected()&&rbTienda.isSelected()&&!rbTrimestre.isSelected()){
            modoDeBusqueda = 4;
            unaInterfazTableroDeMercado.cargarTablaDeVentas((String)comboDeTiendas.getSelectedItem(), Integer.parseInt(txtAnio.getText()),
                    0, modoDeBusqueda);
            
        }else if(rbAnio.isSelected()&&rbTienda.isSelected()&&rbTrimestre.isSelected()){
            modoDeBusqueda = 5;
            unaInterfazTableroDeMercado.cargarTablaDeVentas((String)comboDeTiendas.getSelectedItem(), Integer.parseInt(txtAnio.getText()),
                    Integer.parseInt(txtTrimestre.getText()), modoDeBusqueda);
        }
        
        
        
            
        
        
        
        
    }//GEN-LAST:event_btnFiltroVentasActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFiltroVendedores;
    private javax.swing.JButton btnFiltroVentas;
    private javax.swing.JComboBox<String> comboDeTiendas;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JRadioButton rbAnio;
    private javax.swing.JRadioButton rbTienda;
    private javax.swing.JRadioButton rbTrimestre;
    private javax.swing.JTable tablaDeVendedores;
    private javax.swing.JTable tablaDeVentas;
    private javax.swing.JTextField txtAnio;
    private javax.swing.JTextField txtTrimestre;
    // End of variables declaration//GEN-END:variables


    
    public void cargarTablas(){
        unaInterfazTableroDeMercado.cargarTablaDeVendedores("",0,0,1);
        unaInterfazTableroDeMercado.cargarTablaDeVentas(
                String.valueOf(comboDeTiendas.getSelectedItem()),
                Integer.parseInt(txtAnio.getText()),
                Integer.parseInt(txtTrimestre.getText()), 1);
        
    }
    
    public void cargarTablaDeVentas(List<Object[]> resultados){
        
        modeloTablaDeVentas.setRowCount(0);
        
        Object[] registro = new Object[4];
        for (int i = 0; i < resultados.size(); i++) {

            registro = resultados.get(i);
            modeloTablaDeVentas.addRow(registro);
    
        }
        
    }
    
        
    public void cargarTablaDeVendedores(List<Object[]> vendedores){
        
        modeloTablaDeVendedores.setRowCount(0);
        
        System.out.println("LOS VENDEDORES DESDE EL PANEL DE MERCADO"
                + " "+vendedores);
        
        Object[] registro = new Object[4];
        for (int i = 0; i < vendedores.size(); i++) {
            
            registro = vendedores.get(i);

            modeloTablaDeVendedores.addRow(registro);
          
    
        }
        
    }
    
    public void cargarComboDeTiendas(List<Object[]> registros){
        comboDeTiendas.removeAllItems();
        
        for (int i = 0; i<registros.size() ; i++) {
            
            comboDeTiendas.addItem(String.valueOf(registros.get(i)));

        }
        
        
        
    }



}




