/*
 * This java source file is generated by DAO4J v1.19
 * Generated on Fri Mar 09 06:40:53 CST 2018
 * For more information, please contact b-i-d@163.com
 * Please check http://sourceforge.net/projects/dao4j/ for the latest version.
 */

package modelo;

/*
 * For Table CategoriaUsuario
 */
public class Categoriausuario implements java.io.Serializable, Cloneable {
    private CategoriausuarioKey _key = new CategoriausuarioKey();

    /* categoria, PK */
    protected String categoria;

    /* Return the key object. */
    public CategoriausuarioKey getKeyObject() {
        return _key;
    }

    /* categoria, PK */
    public String getCategoria() {
        return categoria;
    }

    /* categoria, PK */
    public void setCategoria(String categoria) {
        this.categoria = categoria;
        _key.setCategoria(categoria);
    }

    /* Indicates whether some other object is "equal to" this one. */
    public boolean equals(Object obj) {
        if (this == obj)
            return true;

        if (obj == null || !(obj instanceof Categoriausuario))
            return false;

        Categoriausuario bean = (Categoriausuario) obj;

        if (this.categoria == null) {
            if (bean.categoria != null)
                return false;
        }
        else if (!this.categoria.equals(bean.categoria)) 
            return false;

        return true;
    }

    /* Creates and returns a copy of this object. */
    public Object clone()
    {
        Categoriausuario bean = new Categoriausuario();
        bean.categoria = this.categoria;
        return bean;
    }

    /* Returns a string representation of the object. */
    public String toString() {
        String sep = "\r\n";
        StringBuffer sb = new StringBuffer();
        sb.append(this.getClass().getName()).append(sep);
        sb.append("[").append("categoria").append(" = ").append(categoria).append("]").append(sep);
        return sb.toString();
    }
}