/*
 * This java source file is generated by DAO4J v1.19
 * Generated on Fri Mar 09 06:40:53 CST 2018
 * For more information, please contact b-i-d@163.com
 * Please check http://sourceforge.net/projects/dao4j/ for the latest version.
 */

package modelo;

public class CategoriausuarioKey implements java.io.Serializable, Cloneable {
    /* categoria */
    protected String categoria;

    /* categoria */
    public String getCategoria() {
        return categoria;
    }

    /* categoria */
    public void setCategoria(String categoria) {
        this.categoria = categoria;
    }

    /* Calculate hash code */
    public int hashCode() {
        int hashCode = 0;
        if (categoria != null)  
            hashCode += categoria.hashCode();
        return hashCode;
    }
    
    /* Indicates whether some other object is "equal to" this one. */
    public boolean equals(Object obj) {
        if (this == obj)
            return true;

        if (obj == null || !(obj instanceof CategoriausuarioKey))
            return false;

        CategoriausuarioKey key = (CategoriausuarioKey) obj;

        if (this.categoria == null) {
            if (key.categoria != null)
                return false;
        }
        else if (!this.categoria.equals(key.categoria)) 
            return false;

        return true;
    }

    /* Creates and returns a copy of this object. */
    public Object clone()
    {
        CategoriausuarioKey key = new CategoriausuarioKey();
        key.categoria = this.categoria;
        return key;
    }

    /* Returns a string representation of the object. */
    public String toString() {
        String sep = "\r\n";
        StringBuffer sb = new StringBuffer();
        sb.append(this.getClass().getName()).append(sep);
        sb.append("[").append("categoria").append(" = ").append(categoria).append("]");
        return sb.toString();
    }
}