/*
 * This java source file is generated by DAO4J v1.19
 * Generated on Tue Mar 06 22:47:33 CST 2018
 * For more information, please contact b-i-d@163.com
 * Please check http://sourceforge.net/projects/dao4j/ for the latest version.
 */

package modelo;

public class EmpleadotieneventasKey implements java.io.Serializable, Cloneable {
    /* vendedorCURP */
    protected String vendedorcurp;

    /* idVenta */
    protected int idventa;

    /* anio */
    protected int anio;

    /* trimestre */
    protected int trimestre;

    /* vendedorCURP */
    public String getVendedorcurp() {
        return vendedorcurp;
    }

    /* vendedorCURP */
    public void setVendedorcurp(String vendedorcurp) {
        this.vendedorcurp = vendedorcurp;
    }

    /* idVenta */
    public int getIdventa() {
        return idventa;
    }

    /* idVenta */
    public void setIdventa(int idventa) {
        this.idventa = idventa;
    }

    /* anio */
    public int getAnio() {
        return anio;
    }

    /* anio */
    public void setAnio(int anio) {
        this.anio = anio;
    }

    /* trimestre */
    public int getTrimestre() {
        return trimestre;
    }

    /* trimestre */
    public void setTrimestre(int trimestre) {
        this.trimestre = trimestre;
    }

    /* Calculate hash code */
    public int hashCode() {
        int hashCode = 0;
        if (vendedorcurp != null)  
            hashCode += vendedorcurp.hashCode();
        hashCode += new Integer(idventa).hashCode();
        hashCode += new Integer(anio).hashCode();
        hashCode += new Integer(trimestre).hashCode();
        return hashCode;
    }
    
    /* Indicates whether some other object is "equal to" this one. */
    public boolean equals(Object obj) {
        if (this == obj)
            return true;

        if (obj == null || !(obj instanceof EmpleadotieneventasKey))
            return false;

        EmpleadotieneventasKey key = (EmpleadotieneventasKey) obj;

        if (this.vendedorcurp == null) {
            if (key.vendedorcurp != null)
                return false;
        }
        else if (!this.vendedorcurp.equals(key.vendedorcurp)) 
            return false;

        if (this.idventa != key.idventa)
            return false;

        if (this.anio != key.anio)
            return false;

        if (this.trimestre != key.trimestre)
            return false;

        return true;
    }

    /* Creates and returns a copy of this object. */
    public Object clone()
    {
        EmpleadotieneventasKey key = new EmpleadotieneventasKey();
        key.vendedorcurp = this.vendedorcurp;
        key.idventa = this.idventa;
        key.anio = this.anio;
        key.trimestre = this.trimestre;
        return key;
    }

    /* Returns a string representation of the object. */
    public String toString() {
        String sep = "\r\n";
        StringBuffer sb = new StringBuffer();
        sb.append(this.getClass().getName()).append(sep);
        sb.append("[").append("vendedorcurp").append(" = ").append(vendedorcurp).append("]");
        sb.append("[").append("idventa").append(" = ").append(idventa).append("]");
        sb.append("[").append("anio").append(" = ").append(anio).append("]");
        sb.append("[").append("trimestre").append(" = ").append(trimestre).append("]");
        return sb.toString();
    }
}