/*
 * This java source file is generated by DAO4J v1.19
 * Generated on Wed Mar 07 23:27:26 CST 2018
 * For more information, please contact b-i-d@163.com
 * Please check http://sourceforge.net/projects/dao4j/ for the latest version.
 */

package modelo;

public class PartidoKey implements java.io.Serializable, Cloneable {
    /* temporada */
    protected String temporada;

    /* noJornada */
    protected int nojornada;

    /* equipoLocal */
    protected String equipolocal;

    /* equipoVisitante */
    protected String equipovisitante;
    
    public PartidoKey(String temporada,int noJornada,String equipolocal,String equipovisitante){
        this.temporada = temporada;
        this.nojornada = nojornada;
        this.equipolocal = equipolocal;
        this.equipovisitante = equipovisitante;
    }
    
    public PartidoKey(){
        
    }

    /* temporada */
    public String getTemporada() {
        return temporada;
    }

    /* temporada */
    public void setTemporada(String temporada) {
        this.temporada = temporada;
    }

    /* noJornada */
    public int getNojornada() {
        return nojornada;
    }

    /* noJornada */
    public void setNojornada(int nojornada) {
        this.nojornada = nojornada;
    }

    /* equipoLocal */
    public String getEquipolocal() {
        return equipolocal;
    }

    /* equipoLocal */
    public void setEquipolocal(String equipolocal) {
        this.equipolocal = equipolocal;
    }

    /* equipoVisitante */
    public String getEquipovisitante() {
        return equipovisitante;
    }

    /* equipoVisitante */
    public void setEquipovisitante(String equipovisitante) {
        this.equipovisitante = equipovisitante;
    }

    /* Calculate hash code */
    public int hashCode() {
        int hashCode = 0;
        if (temporada != null)  
            hashCode += temporada.hashCode();
        hashCode += new Integer(nojornada).hashCode();
        if (equipolocal != null)  
            hashCode += equipolocal.hashCode();
        if (equipovisitante != null)  
            hashCode += equipovisitante.hashCode();
        return hashCode;
    }
    
    /* Indicates whether some other object is "equal to" this one. */
    public boolean equals(Object obj) {
        if (this == obj)
            return true;

        if (obj == null || !(obj instanceof PartidoKey))
            return false;

        PartidoKey key = (PartidoKey) obj;

        if (this.temporada == null) {
            if (key.temporada != null)
                return false;
        }
        else if (!this.temporada.equals(key.temporada)) 
            return false;

        if (this.nojornada != key.nojornada)
            return false;

        if (this.equipolocal == null) {
            if (key.equipolocal != null)
                return false;
        }
        else if (!this.equipolocal.equals(key.equipolocal)) 
            return false;

        if (this.equipovisitante == null) {
            if (key.equipovisitante != null)
                return false;
        }
        else if (!this.equipovisitante.equals(key.equipovisitante)) 
            return false;

        return true;
    }

    /* Creates and returns a copy of this object. */
    public Object clone()
    {
        PartidoKey key = new PartidoKey();
        key.temporada = this.temporada;
        key.nojornada = this.nojornada;
        key.equipolocal = this.equipolocal;
        key.equipovisitante = this.equipovisitante;
        return key;
    }

    /* Returns a string representation of the object. */
    public String toString() {
        String sep = "\r\n";
        StringBuffer sb = new StringBuffer();
        sb.append(this.getClass().getName()).append(sep);
        sb.append("[").append("temporada").append(" = ").append(temporada).append("]");
        sb.append("[").append("nojornada").append(" = ").append(nojornada).append("]");
        sb.append("[").append("equipolocal").append(" = ").append(equipolocal).append("]");
        sb.append("[").append("equipovisitante").append(" = ").append(equipovisitante).append("]");
        return sb.toString();
    }
}