/*
 * This java source file is generated by DAO4J v1.19
 * Generated on Mon Mar 05 14:30:46 CST 2018
 * For more information, please contact b-i-d@163.com
 * Please check http://sourceforge.net/projects/dao4j/ for the latest version.
 */

package modelo;

/*
 * For Table Posicion
 */
public class Posicion implements java.io.Serializable, Cloneable {
    private PosicionKey _key = new PosicionKey();

    /* posicion, PK */
    protected String posicion;

    /* Return the key object. */
    public PosicionKey getKeyObject() {
        return _key;
    }

    /* posicion, PK */
    public String getPosicion() {
        return posicion;
    }

    /* posicion, PK */
    public void setPosicion(String posicion) {
        this.posicion = posicion;
        _key.setPosicion(posicion);
    }

    /* Indicates whether some other object is "equal to" this one. */
    public boolean equals(Object obj) {
        if (this == obj)
            return true;

        if (obj == null || !(obj instanceof Posicion))
            return false;

        Posicion bean = (Posicion) obj;

        if (this.posicion == null) {
            if (bean.posicion != null)
                return false;
        }
        else if (!this.posicion.equals(bean.posicion)) 
            return false;

        return true;
    }

    /* Creates and returns a copy of this object. */
    public Object clone()
    {
        Posicion bean = new Posicion();
        bean.posicion = this.posicion;
        return bean;
    }

    /* Returns a string representation of the object. */
    public String toString() {
        String sep = "\r\n";
        StringBuffer sb = new StringBuffer();
        sb.append(this.getClass().getName()).append(sep);
        sb.append("[").append("posicion").append(" = ").append(posicion).append("]").append(sep);
        return sb.toString();
    }
}