/*
 * This java source file is generated by DAO4J v1.19
 * Generated on Mon Mar 05 14:30:46 CST 2018
 * For more information, please contact b-i-d@163.com
 * Please check http://sourceforge.net/projects/dao4j/ for the latest version.
 */

package modelo;

public class PosicionKey implements java.io.Serializable, Cloneable {
    /* posicion */
    protected String posicion;

    /* posicion */
    public String getPosicion() {
        return posicion;
    }

    /* posicion */
    public void setPosicion(String posicion) {
        this.posicion = posicion;
    }

    /* Calculate hash code */
    public int hashCode() {
        int hashCode = 0;
        if (posicion != null)  
            hashCode += posicion.hashCode();
        return hashCode;
    }
    
    /* Indicates whether some other object is "equal to" this one. */
    public boolean equals(Object obj) {
        if (this == obj)
            return true;

        if (obj == null || !(obj instanceof PosicionKey))
            return false;

        PosicionKey key = (PosicionKey) obj;

        if (this.posicion == null) {
            if (key.posicion != null)
                return false;
        }
        else if (!this.posicion.equals(key.posicion)) 
            return false;

        return true;
    }

    /* Creates and returns a copy of this object. */
    public Object clone()
    {
        PosicionKey key = new PosicionKey();
        key.posicion = this.posicion;
        return key;
    }

    /* Returns a string representation of the object. */
    public String toString() {
        String sep = "\r\n";
        StringBuffer sb = new StringBuffer();
        sb.append(this.getClass().getName()).append(sep);
        sb.append("[").append("posicion").append(" = ").append(posicion).append("]");
        return sb.toString();
    }
}