/*
 * This java source file is generated by DAO4J v1.19
 * Generated on Wed Mar 07 23:27:26 CST 2018
 * For more information, please contact b-i-d@163.com
 * Please check http://sourceforge.net/projects/dao4j/ for the latest version.
 */

package modelo;

/*
 * For Table RecordDeEquipo
 */
public class Recorddeequipo implements java.io.Serializable, Cloneable {

    private RecorddeequipoKey _key  = new RecorddeequipoKey();

    /* temporada, PK */
    protected String temporada;

    /* nombreEquipo, PK */
    protected String nombreequipo;

    /* partidosGanados */
    protected int partidosganados;

    /* partidosPerdidos */
    protected int partidosperdidos;

    /* partidosEmpatados */
    protected int partidosempatados;

    /* Return the key object. */
    
    public Recorddeequipo(){
        
    }
    public RecorddeequipoKey getKeyObject() {
        return _key;
    }

    /* temporada, PK */
    public String getTemporada() {
        return temporada;
    }

    /* temporada, PK */
    public void setTemporada(String temporada) {
        this.temporada = temporada;
        _key.setTemporada(temporada);
    }

    /* nombreEquipo, PK */
    public String getNombreequipo() {
        return nombreequipo;
    }

    /* nombreEquipo, PK */
    public void setNombreequipo(String nombreequipo) {
        this.nombreequipo = nombreequipo;
        _key.setNombreequipo(nombreequipo);
    }

    /* partidosGanados */
    public int getPartidosganados() {
        return partidosganados;
    }

    /* partidosGanados */
    public void setPartidosganados(int partidosganados) {
        this.partidosganados = partidosganados;
    }

    /* partidosPerdidos */
    public int getPartidosperdidos() {
        return partidosperdidos;
    }

    /* partidosPerdidos */
    public void setPartidosperdidos(int partidosperdidos) {
        this.partidosperdidos = partidosperdidos;
    }

    /* partidosEmpatados */
    public int getPartidosempatados() {
        return partidosempatados;
    }

    /* partidosEmpatados */
    public void setPartidosempatados(int partidosempatados) {
        this.partidosempatados = partidosempatados;
    }

    /* Indicates whether some other object is "equal to" this one. */
    public boolean equals(Object obj) {
        if (this == obj)
            return true;

        if (obj == null || !(obj instanceof Recorddeequipo))
            return false;

        Recorddeequipo bean = (Recorddeequipo) obj;

        if (this.temporada == null) {
            if (bean.temporada != null)
                return false;
        }
        else if (!this.temporada.equals(bean.temporada)) 
            return false;

        if (this.nombreequipo == null) {
            if (bean.nombreequipo != null)
                return false;
        }
        else if (!this.nombreequipo.equals(bean.nombreequipo)) 
            return false;

        if (this.partidosganados != bean.partidosganados)
            return false;

        if (this.partidosperdidos != bean.partidosperdidos)
            return false;

        if (this.partidosempatados != bean.partidosempatados)
            return false;

        return true;
    }

    /* Creates and returns a copy of this object. */
    public Object clone()
    {
        Recorddeequipo bean = new Recorddeequipo();
        bean.temporada = this.temporada;
        bean.nombreequipo = this.nombreequipo;
        bean.partidosganados = this.partidosganados;
        bean.partidosperdidos = this.partidosperdidos;
        bean.partidosempatados = this.partidosempatados;
        return bean;
    }

    /* Returns a string representation of the object. */
    public String toString() {
        String sep = "\r\n";
        StringBuffer sb = new StringBuffer();
        sb.append(this.getClass().getName()).append(sep);
        sb.append("[").append("temporada").append(" = ").append(temporada).append("]").append(sep);
        sb.append("[").append("nombreequipo").append(" = ").append(nombreequipo).append("]").append(sep);
        sb.append("[").append("partidosganados").append(" = ").append(partidosganados).append("]").append(sep);
        sb.append("[").append("partidosperdidos").append(" = ").append(partidosperdidos).append("]").append(sep);
        sb.append("[").append("partidosempatados").append(" = ").append(partidosempatados).append("]").append(sep);
        return sb.toString();
    }
}