/*
 * This java source file is generated by DAO4J v1.19
 * Generated on Mon Mar 05 02:22:23 CST 2018
 * For more information, please contact b-i-d@163.com
 * Please check http://sourceforge.net/projects/dao4j/ for the latest version.
 */

package modelo;

/*
 * For Table TiendaTieneArticulo
 */
public class Tiendatienearticulo implements java.io.Serializable, Cloneable {
    private TiendatienearticuloKey _key = new TiendatienearticuloKey();

    /* nombreTienda, PK */
    protected String nombretienda;

    /* nombreArticulo, PK */
    protected String nombrearticulo;

    /* nombreProveedor, PK */
    protected String nombreproveedor;

    /* existencias */
    protected int existencias;
    
    public Tiendatienearticulo(String nombre,String proveedor,String nombreTienda,int existencias){

        this.existencias = existencias;
        this.nombrearticulo = nombre;
        this.nombreproveedor = proveedor;
        this.nombretienda = nombreTienda;
    }

    public Tiendatienearticulo(){
        
    }
    /* Return the key object. */
    public TiendatienearticuloKey getKeyObject() {
        return _key;
    }

    /* nombreTienda, PK */
    public String getNombretienda() {
        return nombretienda;
    }

    /* nombreTienda, PK */
    public void setNombretienda(String nombretienda) {
        this.nombretienda = nombretienda;
        _key.setNombretienda(nombretienda);
    }

    /* nombreArticulo, PK */
    public String getNombrearticulo() {
        return nombrearticulo;
    }

    /* nombreArticulo, PK */
    public void setNombrearticulo(String nombrearticulo) {
        this.nombrearticulo = nombrearticulo;
        _key.setNombrearticulo(nombrearticulo);
    }

    /* nombreProveedor, PK */
    public String getNombreproveedor() {
        return nombreproveedor;
    }

    /* nombreProveedor, PK */
    public void setNombreproveedor(String nombreproveedor) {
        this.nombreproveedor = nombreproveedor;
        _key.setNombreproveedor(nombreproveedor);
    }

    /* existencias */
    public int getExistencias() {
        return existencias;
    }

    /* existencias */
    public void setExistencias(int existencias) {
        this.existencias = existencias;
    }

    /* Indicates whether some other object is "equal to" this one. */
    public boolean equals(Object obj) {
        if (this == obj)
            return true;

        if (obj == null || !(obj instanceof Tiendatienearticulo))
            return false;

        Tiendatienearticulo bean = (Tiendatienearticulo) obj;

        if (this.nombretienda == null) {
            if (bean.nombretienda != null)
                return false;
        }
        else if (!this.nombretienda.equals(bean.nombretienda)) 
            return false;

        if (this.nombrearticulo == null) {
            if (bean.nombrearticulo != null)
                return false;
        }
        else if (!this.nombrearticulo.equals(bean.nombrearticulo)) 
            return false;

        if (this.nombreproveedor == null) {
            if (bean.nombreproveedor != null)
                return false;
        }
        else if (!this.nombreproveedor.equals(bean.nombreproveedor)) 
            return false;

        if (this.existencias != bean.existencias)
            return false;

        return true;
    }

    /* Creates and returns a copy of this object. */
    public Object clone()
    {
        Tiendatienearticulo bean = new Tiendatienearticulo();
        bean.nombretienda = this.nombretienda;
        bean.nombrearticulo = this.nombrearticulo;
        bean.nombreproveedor = this.nombreproveedor;
        bean.existencias = this.existencias;
        return bean;
    }

    /* Returns a string representation of the object. */
    public String toString() {
        String sep = "\r\n";
        StringBuffer sb = new StringBuffer();
        sb.append(this.getClass().getName()).append(sep);
        sb.append("[").append("nombretienda").append(" = ").append(nombretienda).append("]").append(sep);
        sb.append("[").append("nombrearticulo").append(" = ").append(nombrearticulo).append("]").append(sep);
        sb.append("[").append("nombreproveedor").append(" = ").append(nombreproveedor).append("]").append(sep);
        sb.append("[").append("existencias").append(" = ").append(existencias).append("]").append(sep);
        return sb.toString();
    }
}